name: 'Build'

on:
    workflow_dispatch:
    pull_request:
        types: [ 'opened' ]
        branches: [ 'master' ]
        paths:
        - '**.po'
        - '**.ts'
        - '**.svg'
        - '**.xml'
        - '**.json'
        - '**.css'
        - 'Makefile'
    push:
        branches:
          - 'development'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: sudo apt-get install gettext npm
        - run: make
        - run: make clean
